## Deivis Lopez - Template Bucket-S3
AWSTemplateFormatVersion: "2010-09-09"
Description: Cloud formation for bucket S3 SRE

Parameters:
  BucketName:
    Type: AWS::SSM::Parameter::Value<String> 
    Default: "/fintech2/confidencial/bucketcards"
  BucketNameProd:
    Type: AWS::SSM::Parameter::Value<String> 
    Default: "/fintech2/confidencial/bucketcards/prod"
  Environment:
    Type: String
    Default: 'prod'
    AllowedValues: ['test','prod']
Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']
Resources:  
  MainBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !If [IsProd, !Ref BucketNameProd, !Ref BucketName]
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: SREPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PolicyForAllowUploadWithACL
            Effect: Allow
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref MainBucket
                - /*
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"
      Bucket: !Ref MainBucket
Outputs:
  MainBucketName:
    Description: Nombre del bucket s3
    Value: !Ref MainBucket